### ISSUE TITLE
Centerfusion for 3D object detection.

### ISSUE THREAD

**Issue by 123-afri** [HengWeiBin/CenterFusionDetect3D#1]
Hello, I am a researcher specializing in artificial intelligence, particularly in object detection using sensor fusion. I am utilizing the code provided in your published paper. However, while implementing this code, I encountered an issue. I managed to successfully execute the command 'cd $CF_ROOT python src/convert_nuScenes.py.' However, upon attempting to run the command 'cd $CF_ROOT python src/train.py,' I encountered an error as the 'train.py' file is not present in the repository.Also assist me about test.py file. I kindly request your assistance in resolving this issue. I would greatly appreciate your help.
Kindly response me within 24 hours with complete correct code and description.

**Comment by HengWeiBin** [comment]
Sorry about the outdated of README.md, the new command for training has been updated.
For the test.py, I'm still on progress to completing it.Try [Official code](https://github.com/mrnabati/CenterFusion) if needed.

**Comment by 123-afri** [comment]
Sure, but could you kindly upload the updated train.py file to the repository? Additionally, could you provide an estimate of the completion time for the test.py file? Please upload the train.py file so that I can show my progress to my supervisor. I'll be waiting for the test.py file. I've attempted multiple times to run the official code of the base paper, but unfortunately, it hasn't been successful. Therefore, I would greatly appreciate your assistance in resolving this matter, enabling me to proceed with my research.
Please response me as soon as possible as I continuously working day and night my research.

**Comment by 123-afri** [comment]
I attempted to execute the 'train.py' file, and while it did run partially, it encountered an error at one stage, specifically with the 'centernet_baseline_e170.pth' file, resulting in a FileNotFoundError. Even though I downloaded it from your GitHub repository link "https://github.com/HengWeiBin/CenterFusionDetect3D/releases/download/v1.0.0/centernet_baseline_e170.pt,".
 I also transferred the downloaded folder into the 'models' directory within the code directory, but again the error occured. Additionally, I'd like to inquire about the anticipated duration for the completion of 'test.py'. As I'm deeply engaged in my research day and night. Please explain each and everything about the error and step by step which one run correctly with you. I kindly request a response within 15 hours. I genuinely appreciate your understanding and consideration in this matter. Thank you.
 Muhammad Haroon

**Comment by HengWeiBin** [comment]
The ['centernet_baseline_e170.pth'](https://drive.google.com/uc?export=download&id=1iFF7a5oueFfB5GnUoHFDnntFdTst-bVI) can be download from [official github repo](https://github.com/mrnabati/CenterFusion). But their download link currently seems meet some error.

For the ".pt" file, it's the new format file trained by my code. You should edit `configs/**.yaml`
- set `MODEL.LOAD_DIR` to the model path that you want to load
- _The code support to load both types of weights file in new and old format_

If you want to perform evaluation, try
- set `MODEL.LOAD_DIR` to the model path that you want to evaluate
- set `EVAL = true`
- set `TEST.OFFICIAL_EVAL = true` if you want to get nuscenes' metrics

**Comment by 123-afri** [comment]
I've encountered an error stating "No HIP GPU found" in the code. As I am using NVIDIA RTX2000 GPU and it's hindering my progress on my thesis project. To resolve this issue promptly, I'm considering sharing my computer credentials with you so that you can directly access and run the train.py file on my GPU. This is crucial as I have limited time to complete my thesis, and I've already downloaded the necessary data onto my GPU. I understand that this task may take approximately 1 to 2 hours of your time, and I would be immensely grateful for your assistance. If you agree, I'll provide you with the necessary credentials to begin working on this. Thank you very much for considering my request.

**Comment by HengWeiBin** [comment]
To resolve the GPU problem, I suggest:
1. First, open a new clean virtual environment (ex. anaconda)
2. Then, check your maximum supported cuda version on website or run `nvidia-smi` through command prompt (ps: Make sure `nvidia-smi` can be run to prove that your driver was installed successfully)
3. For example, my cuda version is 12.3, cuda version in pytorch that is below than 12.3 is suitable for me
 ![image](https://github.com/HengWeiBin/CenterFusionDetect3D/assets/45145821/7f32bbc4-e835-4063-b768-1f6f58730b0a)
4. Install pytorch library by using *conda* or *pip* (ex. Command can be found in [Pytorch official website](https://pytorch.org/)
 ![image](https://github.com/HengWeiBin/CenterFusionDetect3D/assets/45145821/08bd638a-591a-411b-84bb-05be1a051e5c)
5. Finally, **make sure** the cuda is available in python before doing next step ${\color{red} Important}$
```
import torch
print(torch.cuda.is_available()
```
![image](https://github.com/HengWeiBin/CenterFusionDetect3D/assets/45145821/9cc37616-b937-48f2-85b6-35c7c520e12d)
