### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Hellohaonan** [HengWeiBin/CenterFusionDetect3D#2]
Thanks for your awesome work. When I run the train process, I met a data type error as the title described. The specific log is as follows:
(centerfusion) xxx@xxx:~/Project/CenterFusionDetect3D$ python src/main.py --cfg configs/centerfusion_full.yaml
wandb is not installed, wandb logging is disabled
=> creating output/CenterFusionFull/2024-07-05-12-48
CONF_THRESH: 0.3
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  COLOR_AUG: True
  DATASET: nuscenes
  FLIP: 0.5
  MAX_CROP: True
  NUM_CLASSES: 10
  NUSCENES:
    MAX_PC: 1000
    MAX_PC_DIST: 60.0
    PC_ROI_METHOD: pillars
    PC_Z_OFFSET: 0.0
    PILLAR_DIMS: (1.5, 0.2, 0.2)
    RADAR_PC: True
  RANDOM_CROP: False
  ROOT: data/
  ROTATE: 0
  SCALE: 0
  SHIFT: 0.2
  TRAIN_SPLIT: mini_train
  VAL_SPLIT: mini_val
DEBUG: 0
EVAL: False
GPUS: (0,)
LOSS:
  NUSCENES_ATT: True
  VELOCITY: True
  WEIGHTS:
    AMODAL_OFFSET: 1
    BBOX: 0.1
    DEPTH: 1
    DIMENSION: 1
    HEATMAP: 1
    NUSCENES_ATT: 1
    ROTATION: 1
    VELOCITY: 1
MIXED_PRECISION: True
MODEL:
  ARCH: dla_34
  DLA:
    NODE: DeformConv
  FREEZE_BACKBONE: False
  FRUSTUM: True
  FUSION_STRATEGY: middle
  GENERIC_NET:
    BACKBONE: dla34
    NECK: dlaup
  INPUT_SIZE: (448, 800)
  K: 100
  LOAD_DIR: models/centernet_baseline_e170.pth
  OUTPUT_SIZE: (112, 200)
NAME: CenterFusionFull
OUTPUT_DIR: output/CenterFusionFull/2024-07-05-12-48
RANDOM_SEED: 0
TEST:
  BATCH_SIZE: 2
  OFFICIAL_EVAL: True
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 30
  LR: 0.00025
  LR_STEP: (220,)
  OPTIMIZER: adam
  RESUME: True
  SAVE_INTERVALS: 10
  SCALE_FACTOR: 16
  SHUFFLE: True
  VAL_INTERVALS: 10
WORKERS: 6
head_conv:
  amodal_offset: [256]
  depth: [256]
  depth2: [256, 256, 256]
  dimension: [256]
  heatmap: [256]
  nuscenes_att: [256, 256, 256]
  reg: [256]
  rotation: [256]
  rotation2: [256, 256, 256]
  velocity: [256, 256, 256]
  widthHeight: [256]
heads:
  amodal_offset: 2
  depth: 1
  depth2: 1
  dimension: 3
  heatmap: 10
  nuscenes_att: 8
  reg: 2
  rotation: 8
  rotation2: 8
  velocity: 3
  widthHeight: 2
layers_to_freeze: ['base', 'dla_up', 'ida_up']
weights:
  amodal_offset: 1
  depth: 1
  depth2: 1
  dimension: 1
  heatmap: 1
  nuscenes_att: 1
  reg: 1
  rotation: 1
  rotation2: 1
  velocity: 1
  widthHeight: 0.1
loaded models/centernet_baseline_e170.pth, epoch 28
Skip loading parameter nuscenes_att.0.weight, required shapetorch.Size([256, 67, 3, 3]), loaded shapetorch.Size([256, 64, 3, 3]).
Skip loading parameter nuscenes_att.2.weight, required shapetorch.Size([256, 256, 1, 1]), loaded shapetorch.Size([8, 256, 1, 1]).
Skip loading parameter nuscenes_att.2.bias, required shapetorch.Size([256]), loaded shapetorch.Size([8]).
Skip loading parameter velocity.0.weight, required shapetorch.Size([256, 67, 3, 3]), loaded shapetorch.Size([256, 64, 3, 3]).
Skip loading parameter velocity.2.weight, required shapetorch.Size([256, 256, 1, 1]), loaded shapetorch.Size([3, 256, 1, 1]).
Skip loading parameter velocity.2.bias, required shapetorch.Size([256]), loaded shapetorch.Size([3]).
No param nuscenes_att.4.weight.
No param nuscenes_att.4.bias.
No param nuscenes_att.6.weight.
No param nuscenes_att.6.bias.
No param velocity.4.weight.
No param velocity.4.bias.
No param velocity.6.weight.
No param velocity.6.bias.
No param depth2.0.weight.
No param depth2.0.bias.
No param depth2.2.weight.
No param depth2.2.bias.
No param depth2.4.weight.
No param depth2.4.bias.
No param depth2.6.weight.
No param depth2.6.bias.
No param rotation2.0.weight.
No param rotation2.0.bias.
No param rotation2.2.weight.
No param rotation2.2.bias.
No param rotation2.4.weight.
No param rotation2.4.bias.
No param rotation2.6.weight.
No param rotation2.6.bias.
<All keys matched successfully>
Resumed optimizer with start lr 0.00025
Number of parameters: 21402320
self.SPLITS[split]: v1.0-mini
loading annotations into memory...
Done (t=0.37s)
creating index...
index created!
Loaded mini_val 486 samples
self.SPLITS[split]: v1.0-mini
loading annotations into memory...
Done (t=1.25s)
creating index...
index created!
Loaded mini_train 1938 samples
                   total.  heatma.  widthH.     reg.   depth.  depth2.  dimens.  rotati.  rotati.  amodal.  nuscen.  veloci.     RAM 
train:   0%|                                                                                                                     | 0/969 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "src/main.py", line 187, in <module>
    main()
  File "src/main.py", line 116, in main
    trainer.train(epoch, train_loader, logger, log)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/trainer.py", line 353, in train
    return self.runEpoch("train", epoch, dataloader, logger, log)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/trainer.py", line 232, in runEpoch
    output, loss, loss_stats = model(batch)
  File "/home/xxx/anaconda3/envs/centerfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/trainer.py", line 148, in forward
    calib=batch["calib"].squeeze(0),
  File "/home/xxx/anaconda3/envs/centerfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/model/networks/base_model.py", line 84, in forward
    feats = self.img2feats(x)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/model/networks/dla.py", line 552, in img2feats
    x = self.dla_up(x)
  File "/home/xxx/anaconda3/envs/centerfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/model/networks/dla.py", line 511, in forward
    ida(layers, len(layers) - i - 2, len(layers))
  File "/home/xxx/anaconda3/envs/centerfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/model/networks/dla.py", line 476, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/xxx/anaconda3/envs/centerfusion/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Project/CenterFusionDetect3D/src/lib/model/networks/dla.py", line 439, in forward
    dilation=self.dilation,
  File "/home/xxx/anaconda3/envs/centerfusion/lib/python3.7/site-packages/torchvision/ops/deform_conv.py", line 85, in deform_conv2d
    n_offset_grps)
RuntimeError: expected scalar type Half but found Float

**Comment by HengWeiBin** [comment]
Thank you for using my work!

Regarding the issue mentioned, please avoid using mixed precision, as it may cause unknown problems and gradient explosion. To configure the settings, edit the [CenterFusionDetect3D/configs/centerfusion_full.yaml](https://github.com/HengWeiBin/CenterFusionDetect3D/blob/main/configs/centerfusion_full.yaml) file and change `MIXED_PRECISION` to false.

We apologize for any inconvenience. A significant update to this repository is planned within the next two months, which will fix the problem and improve the code's performance. Thank you for your patience.
